### Fetch chart-data
GET http://127.0.0.1:8000/chart-data

> {%
client.test("Fetch chart-data", function() { client.assert(response.status === 200, "Cannot fetch chart-data"); });
client.test("Chart-data has the required keys", function() {
    client.assert(response.body.hasOwnProperty("chart_data"), "response does not include chart_data");
    client.assert(response.body.hasOwnProperty("industries"), "response does not include industries");
 });
%}

### Fetch comments
GET http://127.0.0.1:8000/comments

> {%
client.test("Fetch comments", function() {
    client.assert(response.status === 200, "Cannot fetch comments");
});
%}


### Post a new comment
POST http://127.0.0.1:8000/comments
Content-Type: application/json

{
  "username": "Tester",
  "message": "New Comment",
  "year": "2020",
  "industry": "Finance"
}

> {%
client.test("Can create a new comment successfully", function() {
    client.assert(response.status === 201, "Cannot create a new comment");
});
%}


### Post a malformed new comment
POST http://127.0.0.1:8000/comments
Content-Type: application/json

{
  "industry": "NON-EXISTENT-INDUSTRY",
  "username": "Tester",
  "message": "New Comment",
  "year": "2020"
}

> {%
client.test("Returns an error if industry does not exist", function() {
    client.assert(response.status === 400, "Industry does not exist");
});
%}
